project:
  type: website
  output-dir: docs
website:
  title: "Elise LaFreniere"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Internships & Research
      - href: photography.qmd
        text: Film Photography
      - href: publicity-stunt.qmd
        text: Publicity Stunt

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



