project:
  type: website
  output-dir: docs
website:
  title: "Elise LaFreniere"
  navbar:
    background: light      
    foreground: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: research.qmd
        text: Internships & Research
      - href: resume.qmd
        text: Resume
      - href: photography.qmd
        text: Film Photography

format:
  html:
    theme:
      - lux          # The minimalist layout skeleton
      - custom.scss  # Your sage green color overrides
    css: styles.css
    toc: true



